### ISSUE TITLE
貌似从5.10之后就用不了了

### ISSUE THREAD

**Issue by arklee** [WuSiYu/PlasmaVideoWallpaper#3]
现在5.11也是一样，壁纸会直接变成黑色

**Comment by WuSiYu** [comment]
好的，有空修一下

On Oct 30, 2017 12:11 AM, "arklee" <notifications@github.com> wrote:

Closed #3 <https://github.com/WuSiYu/PlasmaVideoWallpaper/issues/3>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/WuSiYu/PlasmaVideoWallpaper/issues/3#event-1315589327>,
or mute the thread
